export const BUYORDER_GET = 'BUYORDER_GET';
export const BUYORDER_GET_SUCCESS = 'BUYORDER_GET_SUCCESS'
export const BUYORDER_GET_FAIL = 'BUYORDER_GET_FAIL'


export const BUYORDER_ADD = 'BUYORDER_ADD';
export const BUYORDER_DELETE = 'BUYORDER_DELETE';
export const BUYORDER_UPDATE = 'BUYORDER_UPDATE';
